- hosts: wp
  # remote_user: "{{ ssh_user }}"
  become: yes
  roles:
      # -
      #   role: upd
      # -
      #   role: php-fpm
      # -
      #   role: mariadb
      -
        role: nginx
        tags: [nginx, web]

