---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: groups.yml
- import_tasks: users.yml
- import_tasks: ssh.yml
