---
- name: Ensure SSH daemon is running.
  service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_sshd_state }}"

- name: sshd_config
  template:
    src: sshd_config.j2
    dest: "{{ security_ssh_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart ssh
