---
# Install soft

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - vim
      - mc
      - git
      - htop
      - wget
      - curl
      - iotop   #
      - strace  #
      - iptraf  #
      - sysstat #
      - nmap
      - net-tools
      - bash-completion
      - tcpdump

#Apache Configuration
- name: Install LAMP Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'apache2', 'mariadb-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]