---

- name: copy ipsec_secrets.j2 -> /etc/ipsec.secrets
  template:
    src: ipsec_secrets.j2
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: 0644
  #notify: reload ipsec

- name: copy ipsec_conf.j2 -> /etc/ipsec.conf
  template:
    src: ipsec_conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644
  notify: restart strongswan

- name: forward sysctl_conf.j2 -> /etc/sysctl.conf
  template:
    src: sysctl_conf.j2
    dest: "{{ sysctl_c }}"
    owner: root
    group: root
    mode: 0644
  notify: reload sysctl

- name: IpTables rules_v4.j2 -> /etc/iptables/rules.v4
  template:
    src: rules_v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0644

# This will load a state from a file, with a rollback in case of access loss
- name: restore firewall state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
  async: "{{ ansible_timeout }}"
  poll: 0
